[package]
name = "voting-system"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
rand = "0.8.4"
druid = "0.7.0"
itertools = "0.8.2"

mpc = { path = "../mpc" }
